In [41]:
import torch
from torch.nn import functional as F
device = 'mps' if torch.backends.mps.is_available() else 'cpu'
print(f"Using device: {device}")

Using device: mps


Exploring PyTorch with just CPU

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-24, -50, -39,  93, -40, -29])

In [4]:
tensor = torch.tensor([[0, 1], [2, 3], [4, 5]])
tensor

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [5]:
zeros = torch.zeros((2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones((2, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
input = torch.empty((2, 3))
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [11]:
linespace = torch.linspace(3, 10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [13]:
logpsace = torch.logspace(start = -10, end = 10, steps = 5)
logpsace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [14]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
a = torch.empty((2,3), dtype =torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

Comparing time against the GPU

In [18]:
import time
import numpy as np

In [19]:
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Time taken to create a zero tensor: {elapsed_time:.6f} seconds")

Time taken to create a zero tensor: 0.003067 seconds


In [23]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = np.random.rand(100, 100, 100, 100)
np_rand2 = np.random.rand(100, 100, 100, 100)

start_time = time.time()
rand_torch = torch_rand1 @ torch_rand2
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Time taken for torch matrix multiplication: {elapsed_time:.6f} seconds")

start_time = time.time()
rand_np = np.multiply(np_rand1, np_rand2)
end_time = time.time()

elapsed_time_np = end_time - start_time
print(f"Time taken for numpy matrix multiplication: {elapsed_time_np:.6f} seconds")

Time taken for torch matrix multiplication: 0.001980 seconds
Time taken for numpy matrix multiplication: 0.732161 seconds


Doing some more exploration

In [27]:
probs = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probs, num_samples=10, replacement=True)
print(f"Samples from multinomial distribution: {samples}")

Samples from multinomial distribution: tensor([0, 1, 1, 1, 1, 0, 1, 1, 1, 1])


In [28]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
out = torch.cat((tensor, tensor), dim=0)
out

tensor([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [29]:
out = torch.tril(torch.ones((3, 3)))
out

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [30]:
out = torch.triu(torch.ones((3, 3)))
out

tensor([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]])

In [31]:
out = torch.zeros(3,3).masked_fill(torch.tril(torch.ones((3,3))) == 0, float('-inf'))
out

tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])

In [32]:
torch.exp(out)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [33]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [34]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked = torch.stack((tensor1, tensor2, tensor3))
stacked

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
import torch.nn.functional as F

In [37]:
tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)
print(f"Softmax output: {softmax_output}")

Softmax output: tensor([0.0900, 0.2447, 0.6652])


In [40]:
a = torch.rand(2, 3, 5)
x, y, z = a.shape
a = a.view(x, y, z)
print(f"Reshaped tensor: {a.shape}")

Reshaped tensor: torch.Size([2, 3, 5])
